/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 20 01:20:39 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.Banco;
import com.example.ContaBancaria;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Banco_ESTest extends Banco_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("", 0.0);
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular("Titular: , Saldo: R$ 0.0");
      assertEquals(0.0, contaBancaria1.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("", 296.21200521);
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular("");
      assertEquals(296.21200521, contaBancaria1.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("", 0.0);
      banco0.adicionarConta(contaBancaria0);
      // Undeclared exception!
      try { 
        banco0.buscarContaPorTitular((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Banco banco0 = new Banco();
      banco0.listarContas();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("3,_4J)/'+EJawA?OW#7", (-437.73636639010687));
      banco0.adicionarConta(contaBancaria0);
      banco0.listarContas();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("3,_4J)/'+EJawA?OW#7", (-437.73636639010687));
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular("3,_4J)/'+EJawA?OW#7");
      assertEquals((-437.73636639010687), contaBancaria1.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("", 0.0);
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular("JIC?1");
      assertNull(contaBancaria1);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Banco banco0 = new Banco();
      banco0.adicionarConta((ContaBancaria) null);
  }
}
