/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 19 22:50:22 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.Banco;
import com.example.ContaBancaria;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Banco_ESTest extends Banco_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("com.example.ContaBancaria", 0.0);
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular(", Saldo: R$ ");
      assertSame(contaBancaria1, contaBancaria0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria(")kI[V5N\"lZ", 1956.18767410267);
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular("");
      assertSame(contaBancaria1, contaBancaria0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Banco banco0 = new Banco();
      banco0.listarContas();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("eOg=w]Tw>{", (-1666.5530816932715));
      banco0.adicionarConta(contaBancaria0);
      banco0.listarContas();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("eOg=w]Tw>{", (-1666.5530816932715));
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular("eOg=w]Tw>{");
      assertEquals((-1666.5530816932715), contaBancaria1.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("eOg=w]Tw>{", (-1666.5530816932715));
      banco0.adicionarConta(contaBancaria0);
      ContaBancaria contaBancaria1 = banco0.buscarContaPorTitular("r\u0007Wn86k..Rj");
      assertNull(contaBancaria1);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Banco banco0 = new Banco();
      ContaBancaria contaBancaria0 = new ContaBancaria("LN5|%_eF>R1$50w", (-3128.11));
      banco0.adicionarConta(contaBancaria0);
      // Undeclared exception!
      try { 
        banco0.buscarContaPorTitular((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Banco banco0 = new Banco();
      banco0.adicionarConta((ContaBancaria) null);
  }
}
