/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 20 01:21:46 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.ContaBancaria;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContaBancaria_ESTest extends ContaBancaria_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("ezyO8EbSL", (-3211.3473404));
      contaBancaria0.depositar(0.0);
      assertEquals((-3211.3473404), contaBancaria0.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria(", Saldo: R$ ", 2632.118849);
      boolean boolean0 = contaBancaria0.sacar(1220.39);
      assertEquals(1411.7288489999999, contaBancaria0.consultarSaldo(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("f=7L", 0.0);
      boolean boolean0 = contaBancaria0.sacar(0.0);
      assertFalse(boolean0);
      assertEquals(0.0, contaBancaria0.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("'}~)&s&(B>_zx:1", 0.0);
      double double0 = contaBancaria0.consultarSaldo();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("RZtZH(_i2<B<d", (-939.294387519228));
      double double0 = contaBancaria0.consultarSaldo();
      assertEquals((-939.294387519228), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria((String) null, 2236.144222493843);
      contaBancaria0.depositar(2236.144222493843);
      assertEquals(4472.288444987686, contaBancaria0.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria((String) null, 2236.144222493843);
      contaBancaria0.depositar((-17.2073212));
      assertEquals(2236.144222493843, contaBancaria0.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria((String) null, 2236.144222493843);
      contaBancaria0.sacar(2236.144222493843);
      boolean boolean0 = contaBancaria0.sacar(2236.144222493843);
      assertEquals(0.0, contaBancaria0.consultarSaldo(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria((String) null, 2236.144222493843);
      boolean boolean0 = contaBancaria0.sacar((-17.2073212));
      assertEquals(2236.144222493843, contaBancaria0.consultarSaldo(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria((String) null, 2236.144222493843);
      String string0 = contaBancaria0.exibirDetalhes();
      assertEquals("Titular: null, Saldo: R$ 2236.144222493843", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria((String) null, 2236.144222493843);
      double double0 = contaBancaria0.consultarSaldo();
      assertEquals(2236.144222493843, double0, 0.01);
  }
}
