/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 19 22:51:28 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.ContaBancaria;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContaBancaria_ESTest extends ContaBancaria_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("uDt|/=9Z1:I^l5h", (-2419.21896841));
      contaBancaria0.depositar((-2419.21896841));
      assertEquals((-2419.21896841), contaBancaria0.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("9", 2070.4285701);
      boolean boolean0 = contaBancaria0.sacar(1.0);
      assertEquals(2069.4285701, contaBancaria0.consultarSaldo(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("$k[PMy e|cN5[tq@3:", (-414.50380032));
      boolean boolean0 = contaBancaria0.sacar((-414.50380032));
      assertEquals((-414.50380032), contaBancaria0.consultarSaldo(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("(", 0.0);
      contaBancaria0.depositar(1.0);
      double double0 = contaBancaria0.consultarSaldo();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria(":]l88w8L~", (-1.0));
      double double0 = contaBancaria0.consultarSaldo();
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("V5", 0.0);
      contaBancaria0.depositar(0.0);
      assertEquals(0.0, contaBancaria0.consultarSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("V5", 0.0);
      contaBancaria0.depositar(4336.740404591365);
      assertEquals(4336.740404591365, contaBancaria0.consultarSaldo(), 0.01);
      
      boolean boolean0 = contaBancaria0.sacar(4336.740404591365);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("V5", 0.0);
      boolean boolean0 = contaBancaria0.sacar(4336.740404591365);
      assertEquals(0.0, contaBancaria0.consultarSaldo(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("V5", 0.0);
      boolean boolean0 = contaBancaria0.sacar(0.0);
      assertEquals(0.0, contaBancaria0.consultarSaldo(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("V5", 0.0);
      String string0 = contaBancaria0.exibirDetalhes();
      assertEquals("Titular: V5, Saldo: R$ 0.0", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ContaBancaria contaBancaria0 = new ContaBancaria("V5", 0.0);
      double double0 = contaBancaria0.consultarSaldo();
      assertEquals(0.0, double0, 0.01);
  }
}
